FitOn/urls.py
from django.contrib import admin
from django.urls import path, include
from metrics.views import get_metric_data
from user.views import loginView

urlpatterns = [
    path("", loginView),
    path("admin/", admin.site.urls),
    path("metrics/", include("metrics.urls")),
    path("user/", include("user.urls")),
    path("exercise/", include("exercise.urls")),
]

metrics/urls.py
from django.urls import path
from .views import get_metric_data, list_metrics, health_data_view, send_report

app_name="metrics"
urlpatterns = [
    path('data/', get_metric_data, name='get_metric_data'),
    path('list/', list_metrics, name='list_metrics'),
    path('submit-health-data/', health_data_view, name='submit_health_data'),
    path('report/', send_report, name='send_report'),
]

metrics/models.py
from django.db import models

# Create your models here.

metrics/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
import matplotlib.pyplot as plt
from asgiref.sync import sync_to_async
import asyncio
import datetime
import pandas as pd
from user.models import User
import random
import requests
import ast
import pytz
import boto3
from django.conf import settings
# from aws_conf import get_dynamodb_resource
from collections import defaultdict

def get_dynamodb_resource():
    id = settings.DYNAMO_ID
    key = settings.DYNAMO_KEY
    return boto3.resource(
        'dynamodb',
        region_name='us-east-2',
        aws_access_key_id=id,
        aws_secret_access_key=key
    )

dataTypes = {
    "heart_rate": "com.google.heart_rate.bpm",
    "resting_heart_rate": "com.google.heart_rate.bpm",
    "steps": "com.google.step_count.delta",
    "sleep": "com.google.sleep.segment",
    "oxygen": "com.google.oxygen_saturation",
    "activity": "com.google.activity.segment",
    "glucose": "com.google.blood_glucose",
    "pressure": "com.google.blood_pressure"
}

df = pd.read_csv('google_fit_activity_types.csv')

#function to convert miliseconds to Day
def parse_millis(millis):
    return datetime.datetime.fromtimestamp(int(millis) / 1000).strftime("%b %d, %I %p")

def list_metrics(request):
    return render(request, 'metrics/metric_list.html')

def steps_barplot(data):
    # Your steps data
    print("inside steps function\n")
    steps_data=[]
    for record in data['bucket']:
        if len(record['dataset'][0]['point'])==0:
            continue
        else:
            d={}
            d['start']=parse_millis(record['startTimeMillis'])
            d['end']=parse_millis(record['endTimeMillis'])
            d['count']=record['dataset'][0]['point'][0]['value'][0]['intVal']
            steps_data.append(d)

    # Pass the plot path to the template
    context = {'steps_data_json': steps_data}
    return context

def heartrate_plot(data):
    print("inside heart function\n")
    heart_data=[]
    for record in data['bucket']:
        if len(record['dataset'][0]['point'])==0:
            continue
        else:
            d={}
            d['start']=parse_millis(record['startTimeMillis'])
            d['end']=parse_millis(record['endTimeMillis'])
            d['count']=float(record['dataset'][0]['point'][0]['value'][0]['fpVal'])
            d['min']=int(record['dataset'][0]['point'][0]['value'][1]['fpVal'])
            d['max']=int(record['dataset'][0]['point'][0]['value'][2]['fpVal'])
            heart_data.append(d)

    # Pass the plot path to the template
    context = {'heart_data_json': heart_data}
    return context

def resting_heartrate_plot(data):
    print("inside resting heart function\n")
    resting_heart_data=[]
    for record in data['bucket']:
        if len(record['dataset'][0]['point'])==0:
            continue
        else:
            d={}
            d['start']=parse_millis(record['startTimeMillis'])
            d['end']=parse_millis(record['endTimeMillis'])
            d['count']=int(record['dataset'][0]['point'][0]['value'][0]['fpVal'])
            resting_heart_data.append(d)

    # Pass the plot path to the template
    context = {'resting_heart_data_json': resting_heart_data}
    return context

def sleep_plot(data):
    print("inside sleep function\n")
    sleep_data=[]
    for record in data['session']:
        d={}
        d['start']=parse_millis(record['startTimeMillis'])
        d['end']=parse_millis(record['endTimeMillis'])
        d['count']=(int(record['endTimeMillis']) - int(record['startTimeMillis']))/1000/60/60
        sleep_data.append(d)

    # Pass the plot path to the template
    context = {'sleep_data_json': sleep_data}
    return context   

def activity_plot(data):
    print("inside activity function\n")
    activity_data={}
    for record in data['session']:
        activity_name = df.loc[df['Integer'] == record['activityType']]['Activity Type'].values
        if len(activity_name) == 0:
            continue
        act=activity_name[0]
        duration=(int(record['endTimeMillis']) - int(record['startTimeMillis']))/1000/60        
        if act in activity_data:
            activity_data[act] += int(duration)
        else:
            activity_data[act] = int(duration)
    
    activity_data = sorted(activity_data.items(), key=lambda x: x[1], reverse=True)
    activity_data = activity_data[:10]

    # Pass the plot path to the template
    context = {'activity_data_json': activity_data}
    return context  

def oxygen_plot(data):
    print("inside oxygen saturation function\n")
    oxygen_data=[]
    for record in data['bucket']:
        if len(record['dataset'][0]['point'])==0:
            continue
        else:
            d={}
            d['start']=parse_millis(record['startTimeMillis'])
            d['end']=parse_millis(record['endTimeMillis'])
            d['count']=int(record['dataset'][0]['point'][0]['value'][0]['fpVal'])
            oxygen_data.append(d)

    # Pass the plot path to the template
    context = {'oxygen_data_json': oxygen_data}
    return context

def glucose_plot(data):
    print("inside blood glucose function\n")
    oxygen_data=[]
    for record in data['bucket']:
        if len(record['dataset'][0]['point'])==0:
            continue
        else:
            d={}
            d['start']=parse_millis(record['startTimeMillis'])
            d['end']=parse_millis(record['endTimeMillis'])
            d['count']=int(record['dataset'][0]['point'][0]['value'][0]['fpVal'])
            oxygen_data.append(d)

    # Pass the plot path to the template
    context = {'glucose_data_json': oxygen_data}
    return context

def pressure_plot(data):
    print("inside blood pressure function\n")
    oxygen_data=[]
    for record in data['bucket']:
        if len(record['dataset'][0]['point'])==0:
            continue
        else:
            d={}
            d['start']=parse_millis(record['startTimeMillis'])
            d['end']=parse_millis(record['endTimeMillis'])
            d['count']=int(record['dataset'][0]['point'][0]['value'][0]['fpVal'])
            oxygen_data.append(d)

    # Pass the plot path to the template
    context = {'pressure_data_json': oxygen_data}
    return context

def get_group_key(time, frequency):
    """Adjusts start and end times based on frequency."""
    if frequency == 'hourly':
        start = time.replace(minute=0, second=0, microsecond=0)
        end = start + datetime.timedelta(hours=1)
    elif frequency == 'daily':
        start = time.replace(hour=0, minute=0, second=0, microsecond=0)
        end = start + datetime.timedelta(days=1)
    elif frequency == 'weekly':
        start = time - datetime.timedelta(days=time.weekday())
        start = start.replace(hour=0, minute=0, second=0, microsecond=0)
        end = start + datetime.timedelta(days=7)
    elif frequency == 'monthly':
        start = time.replace(day=1, hour=0, minute=0, second=0, microsecond=0)
        end = start + datetime.timedelta(days=(time.replace(month=time.month % 12 + 1, day=1) - time).days)
    else:
        start = time  # Fallback to the exact time if frequency is unrecognized
        end = time

    return start, end

def process_dynamo_data(items, frequency):
    # Dictionary to hold the data grouped by date
    print("Items in dictionary", items)
    date_groups = defaultdict(list)

    # Process each item
    for item in items:
        time = datetime.datetime.strptime(item['time'], '%Y-%m-%dT%H:%M')
        start, end = get_group_key(time, frequency)
        start_key = start.strftime('%b %d, %I %p')
        end_key = end.strftime('%b %d, %I %p')
        value = float(item['value'])
        date_groups[(start_key, end_key)].append(value)


    # Prepare the final data structure
    result = []

    for (start_key, end_key), values in date_groups.items():
        avg_count = sum(values) / len(values) if values else 0
        result.append({
            'start': start_key,
            'end': end_key,
            'count': avg_count,
        })

    return {'Items': result}


def merge_data(existing_data, new_data, frequency):
    """
    Merges new data into existing data based on overlapping time ranges defined by frequency.
    
    Parameters:
    existing_data (list): The existing list of data points for a metric.
    new_data (list): The new data points to be merged.
    frequency (str): The frequency of data collection ('hourly', 'daily', 'weekly', 'monthly').

    Returns:
    list: Updated list of data points after merging.
    """
    # Helper to parse datetime from string
    def parse_time(time_str):
        return datetime.datetime.strptime(time_str, '%b %d, %I %p')

    # Create index of existing data by start time for quick access
    data_index = {}
    for item in existing_data:
        start, end = get_group_key(parse_time(item['start']), frequency)
        data_index[start] = item
        item['end_range'] = end  # Temporarily store the range end to use in comparisons

    # Process each new data point
    for new_item in new_data:
        new_start, new_end = get_group_key(parse_time(new_item['start']), frequency)
        if new_start in data_index:
            # There's an overlap, so update the existing entry
            existing_item = data_index[new_start]
            # Averaging the counts, updating mins and maxs
            existing_item['count'] = (existing_item['count'] + new_item['count']) / 2
            existing_item['min'] = min(existing_item['min'], new_item['min'])
            existing_item['max'] = max(existing_item['max'], new_item['max'])
        else:
            # No overlap, append this new item
            new_item['end'] = new_end.strftime('%b %d, %I %p')  # Format end time for consistency
            existing_data.append(new_item)

    # Remove temporary 'end_range' from existing items
    for item in existing_data:

metrics/templates/metrics/display_metric_data.html
{% load static %}
<!DOCTYPE html>
<html lang="en"></html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Health Data</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<style>
    body, html {
        margin: 0;
        padding: 0;
        color: #ffffff;
        font-family: 'Arial', sans-serif;
    }
    
    /* Floating Button Style */
    #addDataButton {
        position: fixed;
        bottom: 20px;
        right: 20px;
        z-index: 9999;
        font-size: 24px;
        background-color: #007BFF;
        color: #ffffff;
        border: none;
        border-radius: 50%;
        width: 60px;
        height: 60px;
        text-align: center;
        line-height: 60px;
        cursor: pointer;
    }
    
    /* Modal styles */
    .modal {
        display: none;
        position: fixed;
        z-index: 1;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgba(0, 0, 0, 0.4);
    }
    
    .modal-content {
        background-color: #fefefe;
        margin: 15% auto;
        width: 50% !important;
        padding: 20px;
        border: 1px solid #888;
    }
    
    .close {
        color: #aaaaaa;
        float: right;
        text-align: end;
        font-size: 28px;
        font-weight: bold;
        transition: color 0.3s ease;
    }
    
    .close:hover,
    .close:focus {
        color: #000000;
        text-decoration: none;
        cursor: pointer;
    }

</style>

</head>
<body>
    {% include "user/navbar.html" %}
    <link rel="stylesheet" href="{% static 'metrics/css/display_metric_data.css' %}">
    {% if data %}

    <!-- Floating Action Button -->
    <button id="addDataButton">+</button>

    <!-- The Modal -->
    <div id="dataModal" class="modal">

        <!-- Modal content -->
        <div class="modal-content">
            <span class="close">&times;</span>
            <form method="post" action="{% url 'metrics:submit_health_data' %}">
                {% csrf_token %}
                <label for="metric">Metric:</label>
                <select name="metric" id="metric" class="my-1">
                    <option value="heart_rate">Heart Rate</option>
                    <option value="oxygen">Oxygen Saturation</option>
                    <option value="steps">Steps</option>
                    <option value="resting_heart_rate">Resting Heart Rate</option>
                    <option value="sleep">Sleep</option>
                    <option value="activity">Exercises</option>
                    <option value="glucose">Blood Glucose</option>
                    <option value="pressure">Blood Pressure</option>
                    <!-- Add other metrics options as needed -->
                </select>
                <br>
                <label for="time">Time:</label>
                <input type="datetime-local" name="time" required class="my-1">
                <br>
                <label for="value">Value:</label>
                <input type="number" name="value" required class="my-1">
                <br>
                <input type="submit" value="Save" class="btn btn-primary mt-5">
            </form>
        </div>

    </div>

    <div class="search-and-filter py-4 mt-0 mb-5">
        <div class="filter-left-column container mx-0 mr-5">
            <div class="row">
                <p class='display-4'>Home Dashboard</p>
            </div>
        </div>
        <div class="filter-right-column container col-6 pl-5">
            <form method="get" class="filter-form" id="filter-form">
                <fieldset id="filter-fieldset">
                    <legend>
                        <div class="row">
                            <div class="col text-left">FILTERS</div>
                            <button class="col-md-2 text-right btn btn-primary text-center mr-3">Apply</button>
                        </div>
                    </legend>
                    <hr class="mt-0 mb-3"/>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="data_length">Data Duration:</label>
                                <select class="custom-select" id="data_drn" name="data_drn" onchange="handleDurationChange()">
                                    {% comment %} <option value="hour">Past Hour</option> {% endcomment %}
                                    <option value="day">Past Day</option>
                                    <option value="week">Past Week</option>
                                    <option value="month">Past Month</option>
                                    <option value="quarter">Past Quarter</option>
                                </select>
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="data_freq">Data Frequency:</label>
                                <select class="custom-select" id="data_freq" name="data_freq">
                                    {% comment %} <option value="per_min">Per Minute</option> {% endcomment %}
                                    <option value="hourly">Per Hour</option>
                                    <option value="daily">Per Day</option>
                                    <option value="weekly">Per Week</option>
                                    <option value="monthly">Per Month</option>
                                </select>
                            </div>
                        </div>
                        <div class="col">
                        </div>
                    </div>
                </fieldset>
                <button type="submit" hidden></button>
            </form>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row my-5">
            <div class="col-md-6">
                <h2>Steps Count</h2>
                <canvas id="stepsChart"></canvas>
            </div>
            <div class="col-md-6">
                <h2>Heart Rate</h2>
                <canvas id="heartRateChart"></canvas>
            </div>
        </div>
        <div class="row my-5">
            <div class="col-md-6 container" style="height: 450px; margin-bottom: 50px">
                <h2>Sleep Data</h2>
                <canvas id="sleepChart"></canvas>
            </div>
            <div class="col-md-6">
                <h2>Blood Oxygen Levels</h2>
                <canvas id="oxygenChart"></canvas>
            </div>
        </div>
        <div class="row my-5">
            <div class="col-md-6">
                <h2>Body Fitness</h2>
                <canvas id="bodyFitnessChart"></canvas>
            </div>
            <div class="col-md-6">
                <h2>Top Activities</h2>
                <table border="1">
                    <thead>
                        <tr>
                            <th>Exercise</th>
                            <th>Duration (in minutes)</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for activity_data in data.activity.activity_data_json %}
                        <tr>
                            <td>{{ activity_data.0 }}</td>
                            <td>{{ activity_data.1 }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script>
        // Get steps data from Django template context
        let total_data = {{data|safe}};
    </script>
    {% endif %}
</body>

<script src="{% static 'metrics/javascript/display_metric_data.js' %}"></script>
</html>

metrics/templates/metrics/metric_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Metric Types</title>
</head>
<body>
    <h1>List of Available Metric Data</h1>
    <ul>
        <li><a href="{% url 'metrics:get_metric_data' metric='heart_rate' %}">Heart Rate</a></li>
        <li><a href="{% url 'metrics:get_metric_data' metric='resting_heart_rate' %}">Resting Heart Rate</a></li>
        <li><a href="{% url 'metrics:get_metric_data' metric='steps' %}">Step Count</a></li>
        <li><a href="{% url 'metrics:get_metric_data' metric='sleep' %}">Sleep</a></li>
        <li><a href="{% url 'metrics:get_metric_data' metric='exercise' %}">Exercise</a></li>
    </ul>
</body>
</html>